# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hacker-news' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hacker-news

  pod 'Firebase/Core'


  target 'hacker-newsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
